model:
  base_learning_rate: 1.0e-06
  target: model.sr3_modules.ddpm.LatentDiffusion
  params:
    loss_type: l1
    first_stage_key: image
    cond_stage_key: image
    image_size: 32
    channels: 3

    scheduler_config: # 10000 warmup steps
      target: lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [10000]
        cycle_lengths: [10000000000000]
        f_start: [1.e-6]
        f_max: [1.]
        f_min: [1.]

    unet_config:
      target: model.sr3_modules.unet.UNet
      params:
        in_channels: 6
        out_channels: 3
        inner_channel: 64,
        attn_res:
          - 16
        num_res_blocks: 2
        channel_mult:
          - 1
          - 2
          - 4
          - 8
          - 8
        res_blocks: 2
        dropout: 0.2

    first_stage_config:
      target: model.sr3_modules.autoencoder.VQModelInterface
      params:
        embed_dim: 3
        n_embed: 8192
        ckpt_path: /content/drive/MyDrive/ckpts/VQVAE-epoch=10.ckpt
        ddconfij:
          double_z: false
          z_channels: 3
          resolution: 512
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
            - 1
            - 2
            - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config: __is_unconditional__

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 8
    num_workers: 5
    wrap: False
    train:
      target: ldm.data.kvasir.KvasirSegTrain
      params:
        size: 512
    validation:
      target: ldm.data.kvasir.KvasirSegEval
      params:
        size: 512

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 5000
        max_images: 8
        increase_log_steps: False

  trainer:
    benchmark: True
